name: Build and Deploy .NET API to App Service and APIM

on:
  push:
    branches:
      - main   # Trigger when you edit files in GitHub browser

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    # -------------------------------
    # 1. Checkout source code
    # -------------------------------
    - name: Checkout code
      uses: actions/checkout@v4

    # -------------------------------
    # 2. Setup .NET SDK
    # -------------------------------
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '7.0.x'

    # -------------------------------
    # 3. Restore dependencies
    # -------------------------------
    - name: Restore dependencies
      run: dotnet restore

    # -------------------------------
    # 4. Build project
    # -------------------------------
    - name: Build
      run: dotnet build --configuration Release --no-restore

    # -------------------------------
    # 5. Publish project
    # -------------------------------
    - name: Publish
      run: dotnet publish -c Release -o publish

    # -------------------------------
    # 6. Login to Azure
    # -------------------------------
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # -------------------------------
    # 7. Deploy to Azure App Service
    # -------------------------------
    - name: Deploy to App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: AppServicemahesh
        package: publish

    # -------------------------------
    # 8. Import API into APIM
    # -------------------------------
    - name: Import API to APIM
      run: |
        az apim api import \
          --resource-group AppServiceresourcegroupmahesh \
          --service-name Apimmahesh \
          --api-id dotnet-api \
          --path dotnet \
          --specification-format OpenApi \
          --specification-path ./publish/swagger/v1/swagger.json \
          --service-url https://appservicemahesh.azurewebsites.net \
          --subscription-required false
